const restaurantData = [
    { id: 1, title: "Kennington Lane Cafe", description: "Non enim praesent elementum facilisis leo vel fringilla. Lectus proin nibh nisl condimentum id. Quis varius quam quisque id diam vel.", buttons: ["american", "steakhouse", "seafood"], image: "https://via.placeholder.com/150", animation: "flip-up" },
    { id: 2, title: "The Wilmington", description: "Eu mi bibendum neque egestas congue quisque. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Odio ut sem nulla pharetra diam sit amet.", buttons: ["american", "steakhouse", "seafood"], image: "https://via.placeholder.com/150", animation: "flip-down" },
    { id: 3, title: "Kings Arms", description: "Nunc lobortis mattis aliquam faucibus. Nibh ipsum consequat nisl vel pretium lectus quam id leo. A scelerisque purus semper eget. Tincidunt arcu non.", buttons: ["healthy", "steakhouse", "vegetarian"], image: "https://via.placeholder.com/150", animation: "flip-up" },
    { id: 4, title: "The Ivy City Garden", description: "Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at.", buttons: ["italian", "bar", "grill"], image: "https://via.placeholder.com/150", animation: "flip-down" },
    { id: 5, title: "Dishoom Shoreditch", description: "Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan sit.", buttons: ["indian", "vegetarian", "vegan"], image: "https://via.placeholder.com/150", animation: "flip-up" },
    { id: 6, title: "Burger & Lobster", description: "Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida arcu.", buttons: ["burgers", "seafood", "grill"], image: "https://via.placeholder.com/150", animation: "flip-down" },
    { id: 7, title: "Kennington Lane Cafe", description: "Non enim praesent elementum facilisis leo vel fringilla. Lectus proin nibh nisl condimentum id. Quis varius quam quisque id diam vel.", buttons: ["american", "steakhouse", "seafood"], image: "https://via.placeholder.com/150", animation: "flip-up" },
];

export default restaurantData;